name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.42.0  # Use the Playwright image

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'yarn'
    
    - name: Cache Eslint dependencies
      uses: actions/cache@v3
      with: 
        path: ./.cache/eslint
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}-${{ hashFiles('**/.eslintrc.cjs') }}
        restore-keys: |
          ${{ runner.os }}-eslint-

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Lint
      run: yarn lint:ci

    - name: Test
      run: yarn test  # Playwright is already installed in the container

    - name: Build
      run: yarn build
